// Code generated by "stringer -type ObjectType"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NullObj-1]
	_ = x[ErrorObject-2]
	_ = x[ReturnValueObject-3]
	_ = x[IntegerObject-4]
	_ = x[StringObj-5]
	_ = x[ArrayObject-6]
	_ = x[HashObject-7]
	_ = x[NumberObj-8]
	_ = x[BuiltinObj-9]
}

const _ObjectType_name = "NullObjErrorObjectReturnValueObjectIntegerObjectStringObjArrayObjectHashObjectNumberObjBuiltinObj"

var _ObjectType_index = [...]uint8{0, 7, 18, 35, 48, 57, 68, 78, 87, 97}

func (i ObjectType) String() string {
	i -= 1
	if i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
