// Code generated by "stringer -type Type"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NullType-1]
	_ = x[ErrorType-2]
	_ = x[ReturnValueType-3]
	_ = x[IntegerType-4]
	_ = x[StringType-5]
	_ = x[ArrayType-6]
	_ = x[HashType-7]
	_ = x[NumberType-8]
	_ = x[BuiltinType-9]
	_ = x[FunctionType-10]
	_ = x[BooleanType-11]
}

const _ObjectType_name = "NullTypeErrorTypeReturnValueTypeIntegerTypeStringTypeArrayTypeHashTypeNumberTypeBuiltinTypeFunctionTypeBooleanType"

var _ObjectType_index = [...]uint8{0, 8, 17, 32, 43, 53, 62, 70, 80, 91, 103, 114}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_ObjectType_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
